version: 2
jobs:
  build:
    docker:
      - image: docker:17.06.0-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t enjoy2000/circleci-centos-python:circleci .
      - deploy:
          name: Tag docker images
          command: |
            docker tag enjoy2000/circleci-centos-python:circleci enjoy2000/circleci-centos-python
      - deploy:
          name: Login to Docker Hub
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - deploy:
          name: Push docker images
          command: |
            docker push enjoy2000/circleci-centos-python
